### ISSUE TITLE
 Output directories must be flagged with directory()

### ISSUE THREAD

**Issue by Puputnik** [hyunhwaj/SalmonTE#14]
Hello, i tried to run SalmonTE both on example data and on my own data, and the tool is failing.
This is the terminal output:
`SalmonTE.py quant --reference=hs '/home/filippo/SalmonTE/example/CTRL_1_R1.fastq' '/home/filippo/SalmonTE/example/CTRL_1_R2.fastq' 
2018-07-27 17:42:44,688 Starting quantification mode
2018-07-27 17:42:44,688 Collecting FASTQ files...
['/home/filippo/SalmonTE/example/CTRL_1_R1.fastq', '/home/filippo/SalmonTE/example/CTRL_1_R2.fastq']
2018-07-27 17:42:44,688 The input dataset is considered as a paired-ends dataset.
CTRL_1_R1.fastq CTRL_1_R2.fastq
2018-07-27 17:42:44,688 Collected 1 FASTQ files.
2018-07-27 17:42:44,688 Quantification has been finished.
2018-07-27 17:42:44,688 Running Salmon using Snakemake
Building DAG of jobs...
2018-07-27 17:42:44,749 Building DAG of jobs...
Using shell: /bin/bash
2018-07-27 17:42:44,757 Using shell: /bin/bash
Provided cores: 1
2018-07-27 17:42:44,757 Provided cores: 1
Rules claiming more threads will be scaled down.
2018-07-27 17:42:44,757 Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	run_salmon_fq
	3
2018-07-27 17:42:44,757 Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	run_salmon_fq
	3

2018-07-27 17:42:44,758 
rule run_salmon_fq:
    input: /home/filippo/SalmonTE/reference/hs, /tmp/tmp9fe3ywrf/CTRL_1_R1.fastq, /tmp/tmp9fe3ywrf/CTRL_1_R2.fastq
    output: /home/filippo/SalmonTE_output/CTRL_1
    jobid: 2
    wildcards: sample_fq=CTRL_1
2018-07-27 17:42:44,758 rule run_salmon_fq:
    input: /home/filippo/SalmonTE/reference/hs, /tmp/tmp9fe3ywrf/CTRL_1_R1.fastq, /tmp/tmp9fe3ywrf/CTRL_1_R2.fastq
    output: /home/filippo/SalmonTE_output/CTRL_1
    jobid: 2
    wildcards: sample_fq=CTRL_1

2018-07-27 17:42:44,758 
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
ImproperOutputException in line 17 of /home/filippo/SalmonTE/snakemake/Snakefile.paired:
Outputs of incorrect type (directories when expecting files or vice versa). Output directories must be flagged with directory(). for rule run_salmon_fq:
/home/filippo/SalmonTE_output/CTRL_1
2018-07-27 17:42:45,267 ImproperOutputException in line 17 of /home/filippo/SalmonTE/snakemake/Snakefile.paired:
Outputs of incorrect type (directories when expecting files or vice versa). Output directories must be flagged with directory(). for rule run_salmon_fq:
/home/filippo/SalmonTE_output/CTRL_1
Removing output files of failed job run_salmon_fq since they might be corrupted:
/home/filippo/SalmonTE_output/CTRL_1
2018-07-27 17:42:45,268 Removing output files of failed job run_salmon_fq since they might be corrupted:
/home/filippo/SalmonTE_output/CTRL_1
Skipped removing non-empty directory /home/filippo/SalmonTE_output/CTRL_1
2018-07-27 17:42:45,268 Skipped removing non-empty directory /home/filippo/SalmonTE_output/CTRL_1
Shutting down, this might take some time.
2018-07-27 17:42:45,270 Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
2018-07-27 17:42:45,270 Exiting because a job execution failed. Look above for error message
Complete log: /home/filippo/.snakemake/log/2018-07-27T174244.739266.snakemake.log
2018-07-27 17:42:45,271 Complete log: /home/filippo/.snakemake/log/2018-07-27T174244.739266.snakemake.log
Traceback (most recent call last):
  File "/home/filippo/SalmonTE/SalmonTE.py", line 276, in <module>
    run(args)
  File "/home/filippo/SalmonTE/SalmonTE.py", line 235, in run
    run_salmon(param)
  File "/home/filippo/SalmonTE/SalmonTE.py", line 153, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/filippo/SalmonTE_output/EXPR.csv'`

can you help me?

**Comment by quirze** [comment]
Hello,
I've experienced the same issue, also both on my own data and on the example data of the repository.
It looks like there might be a bug in the file `snakemake/Snakefile.paired`.
I would also appreciate some help. Thank you.

**Comment by hyunhwaj** [comment]
@Puputnik and @quirze,

Can you show me the list of files in `SalmonTE_output` directory using commanding `ls SalmonTE_output/*`? What is your version of `snakemake` (you can look it up using `snakemake -v`)?

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
@quirze what about the version of the `snakemake`? I am also wondering how many FASTQ files are in your `/home/qrovira/bin/SalmonTE/example_single` directory. Do you only have a pair of FASTQ files? But I am seeing `2018-07-27 18:11:56,177 Collected 4 FASTQ files.` It would be helpful you show me the output of `tree /home/qrovira/bin/SalmonTE/example_single` and head of each fastq file in the directory.

Thank you!

Hyun-Hwan Jeong

**Comment by quirze** [comment]
When I check the version of `snakemake` I get an error as if I haven't got installed:
```
[qrovira@node-head1 ~]$ snakemake -h
-bash: snakemake: command not found
```
However, I did run `pip3 install snakemake` with no errors.

Regarding to the FASTQ files, I used the ones in the example to test pair-end reads and then I took only the first mate to try the single-end mode:
```
[qrovira@node-head1 ~]$ tree /home/qrovira/bin/SalmonTE/example_single
/home/qrovira/bin/SalmonTE/example_single
├── CTRL_1_R1.fastq
├── CTRL_2_R1.fastq
├── TARDBP_1_R1.fastq
└── TARDBP_2_R1.fastq

0 directories, 4 files
[qrovira@node-head1 ~]$ tree /home/qrovira/bin/SalmonTE/example
/home/qrovira/bin/SalmonTE/example
├── CTRL_1_R1.fastq
├── CTRL_1_R2.fastq
├── CTRL_2_R1.fastq
├── CTRL_2_R2.fastq
├── TARDBP_1_R1.fastq
├── TARDBP_1_R2.fastq
├── TARDBP_2_R1.fastq
└── TARDBP_2_R2.fastq

0 directories, 8 files
```
Is there a problem with the snakemake installation?

**Comment by frankyan** [comment]
I also encountered this problem. My problem was caused by Snakemakes version 5.2. Since version 5.2, directory outputs have to marked with `directory`. Then I installed Snakemakes version 5.1.5. Everything is ok now.

**Comment by hyunhwaj** [comment]
@frankyan thanks for reporting that. Yes, you're right. There is an incompatibility between the `SalmonTE` rules and the latest version of `snakemake`. I will look for the issue. 

@quirze and @Puputnik, could you please uninstall your current `snakemake` installation and install the `snakemake 5.1.5` to see whether it solves your issue?

Thank you all!

Hyun-Hwan Jeong

**Comment by quirze** [comment]
Indeed, after uninstalling `snakemake` and installing the version `5.1.5` now I get no error when running `SalmonTE`.
```
pip3 uninstall snakemake
pip3 install -Iv snakemake==5.1.5
```
Thank you for the help.

**Comment by Puputnik** [comment]
Thank you Very much! Tomorrow morning i Will check if it works.

Thank you again!

Il 29/Lug/2018 23:03, "Quirze" <notifications@github.com> ha scritto:

**Comment by Puputnik** [comment]
working also for me!

Thank you very much.

2018-07-29 23:38 GMT+02:00 filippo martignano <filippo.martignano@gmail.com>
:

**Comment by hyunhwaj** [comment]
@Puputnik and @quirze glad to hear you've solved the issue, and thanks to @frankyan, again! I will look for it how to fix the issue for the latest version of `snakemake`.

Best,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
Now `SalmonTE` can work with the latest version of `snakemake`!

Hyun-Hwan Jeong

**Comment by shishimin** [comment]
Hi， hyunhwaj 
When i uninstalled snakemake and install the version 5.1.5 now I get also get the same error when running SalmonTE like the following:
[ssmin@SKLMG10 ADcase]$ snakemake -v
5.1.5
[ssmin@SKLMG10 ADcase]$ SalmonTE.py quant --reference=hs --outpath=SalmonTE/ --num_threads=6 /zs32/home/ssmin/softwares/SalmonTE-master/example/CTRL_1_R1.fastq
2019-05-28 09:30:58,384 Starting quantification mode
2019-05-28 09:30:58,384 Collecting FASTQ files...
2019-05-28 09:30:58,387 The input dataset is considered as a single-end dataset.
2019-05-28 09:30:58,387 Collected 1 FASTQ files.
2019-05-28 09:30:58,387 Quantification has been finished.
2019-05-28 09:30:58,387 Running Salmon using Snakemake
NameError in line 24 of /zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single:
name 'directory' is not defined
  File "/zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single", line 24, in <module>
2019-05-28 09:30:58,590 NameError in line 24 of /zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single:
name 'directory' is not defined
  File "/zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single", line 24, in <module>
Traceback (most recent call last):
  File "/zs32/home/ssmin/softwares/SalmonTE-master/SalmonTE.py", line 289, in <module>
    run(args)
  File "/zs32/home/ssmin/softwares/SalmonTE-master/SalmonTE.py", line 240, in run
    run_salmon(param)
  File "/zs32/home/ssmin/softwares/SalmonTE-master/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'SalmonTE/EXPR.csv'
[ssmin@SKLMG10 ADcase]$ SalmonTE.py quant --reference=hs --outpath=SalmonTE/ --num_threads=6 Liu-AS-10_S10_L001_R1_001.fastq.gz
2019-05-28 09:31:10,209 Starting quantification mode
2019-05-28 09:31:10,209 Collecting FASTQ files...
2019-05-28 09:31:10,211 The input dataset is considered as a single-end dataset.
2019-05-28 09:31:10,211 Collected 1 FASTQ files.
2019-05-28 09:31:10,211 Quantification has been finished.
2019-05-28 09:31:10,211 Running Salmon using Snakemake
NameError in line 24 of /zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single:
name 'directory' is not defined
  File "/zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single", line 24, in <module>
2019-05-28 09:31:10,422 NameError in line 24 of /zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single:
name 'directory' is not defined
  File "/zs32/home/ssmin/softwares/SalmonTE-master/snakemake/Snakefile.single", line 24, in <module>
Traceback (most recent call last):
  File "/zs32/home/ssmin/softwares/SalmonTE-master/SalmonTE.py", line 289, in <module>
    run(args)
  File "/zs32/home/ssmin/softwares/SalmonTE-master/SalmonTE.py", line 240, in run
    run_salmon(param)
  File "/zs32/home/ssmin/softwares/SalmonTE-master/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'SalmonTE/EXPR.csv'

 For my data and example data, I got the same error.
Can you help me?
