### ISSUE TITLE
Empty ouput for fastq.gz files

### ISSUE THREAD

**Issue by adomingues** [hyunhwaj/SalmonTE#8]
Sorry again Hwan but I am seem to be good at breaking things.

This time I would like to report an issue with using compressed fastq files. These are two unexpected errors or outputs when using my data which is in `fastq.gz` format. For debugging I have used the example data contained in `SalmonTE` because it works as described in the ` Readme` for uncompressed data. I then compressed the example data and tried to run `SalmonTE` on it:
 
```bash
cd example/
for f in *.fastq; do gzip $f; done
cd ..
SalmonTE.py quant --reference=hs example
2018-01-29 15:54:26,614 Starting quantification mode
2018-01-29 15:54:26,614 Collecting FASTQ files...
2018-01-29 15:54:26,620 File extensions of all files must be same.
```

The error points at an issue with the file extensions but these appear to be ok:

```sh
ls example/
CTRL_1_R1.fastq.gz  CTRL_1_R2.fastq.gz  CTRL_2_R1.fastq.gz  CTRL_2_R2.fastq.gz  TARDBP_1_R1.fastq.gz  TARDBP_1_R2.fastq.gz  TARDBP_2_R1.fastq.gz  TARDBP_2_R2.fastq.gz
```

Using the paired reads of a single sample avoids the above error and `SalmonTE` runs to completion:

```sh
SalmonTE.py quant --reference=hs example/CTRL_1_R1.fastq.gz example/CTRL_1_R2.fastq.gz
2018-01-29 15:54:52,250 Starting quantification mode
2018-01-29 15:54:52,250 Collecting FASTQ files...
2018-01-29 15:54:52,253 The input dataset is considered as a single-end dataset.
2018-01-29 15:54:52,253 Collected 1 FASTQ files.
2018-01-29 15:54:52,253 Quantification has been finished.
2018-01-29 15:54:52,253 Running Salmon using Snakemake
Building DAG of jobs...
2018-01-29 15:54:52,843 Building DAG of jobs...
Using shell: /bin/bash
2018-01-29 15:54:52,995 Using shell: /bin/bash
Provided cores: 1
2018-01-29 15:54:52,995 Provided cores: 1
Rules claiming more threads will be scaled down.
2018-01-29 15:54:52,996 Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       collect_abundance
        2
2018-01-29 15:54:52,996 Job counts:
        count   jobs
        1       all
        1       collect_abundance
        2

2018-01-29 15:54:52,997 
rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1
2018-01-29 15:54:52,997 rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1

2018-01-29 15:54:52,997 
Finished job 1.
2018-01-29 15:54:55,637 Finished job 1.
1 of 2 steps (50%) done
2018-01-29 15:54:55,638 1 of 2 steps (50%) done

2018-01-29 15:54:55,640 
localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0
2018-01-29 15:54:55,640 localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0

2018-01-29 15:54:55,641 
Finished job 0.
2018-01-29 15:54:55,642 Finished job 0.
2 of 2 steps (100%) done
2018-01-29 15:54:55,643 2 of 2 steps (100%) done
Shutting down, this might take some time.
2018-01-29 15:54:55,644 Shutting down, this might take some time.
Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-01-29T155452.783513.snakemake.log
2018-01-29 15:54:55,644 Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-01-29T155452.783513.snakemake.log

```

However it doesn't seem to perform any quantifications:

```sh
cat SalmonTE_output/EXPR.csv
TE
```

`TE` is literally the only thing written to `EXPR.csv`.

---

I have now extracted my reads to `fastq` files and I am using these to run SalmonTE, which is good enough workaround. Just letting you know about these issues.

All the best and sorry again for all these bug reports. 

António

**Comment by hyunhwaj** [comment]
This looks a different issue to #7, but the origin of the problems are same, so I labeled this issue as *duplicated*. Now I uploaded a patch of the problem. 

Thanks again,

Hwan

**Comment by adomingues** [comment]
Thank you for the quick reply, but sadly the problem does not appear to have been solved for me. Bellow is what I did to test.

First updated the SalmonTE:

```sh
git pull
Updating 5759736..76e8506
Fast-forward
 SalmonTE.py                | 24 ++++++++++++++++--------
 snakemake/Snakefile.paired | 29 ++++++++++++++++++++++-------
 snakemake/Snakefile.single | 26 ++++++++++++++++++++------
 3 files changed, 58 insertions(+), 21 deletions(-)
```

Then compressed the files as previously, and ran the example:

```sh
cd example/
for f in *.fastq; do gzip $f; done
cd ..

SalmonTE.py quant --reference=hs example
2018-01-30 21:01:19,475 Starting quantification mode
2018-01-30 21:01:19,475 Collecting FASTQ files...
2018-01-30 21:01:19,595 The input dataset is considered as a paired-ends dataset.
Traceback (most recent call last):
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 270, in <module>
    run(args)
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 224, in run
    param = {**args, **collect_FASTQ_files(args['FILE'])}
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 114, in collect_FASTQ_files
    os.symlink(os.path.abspath(a), os.path.join(tmp_dir, trim_a))
FileExistsError: [Errno 17] File exists: '/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/example/CTRL_2_R1.fastq.gz' -> '/tmp/tmpz
9hnjo93/_R1.fastq.gz'
```

This is a different error so I checked what is insided the folder `/tmp/tmpz9hnjo93/` and it contains (incomplete?) symbolic links to some of the data files:

```sh
ll /tmp/tmpz9hnjo93/                                                                                     
total 1.1M
drwx------    2 adomingu imb  4.0K Jan 30 21:01 ./
drwxrwxrwt 1178 root     root 1.1M Jan 30 21:02 ../
lrwxrwxrwx    1 adomingu imb    82 Jan 30 21:01 _R1.fastq.gz -> /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/example/CTRL_1_R1.f
astq.gz
lrwxrwxrwx    1 adomingu imb    82 Jan 30 21:01 _R2.fastq.gz -> /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/example/CTRL_1_R2.f
astq.gz
```

Then I tested, as before, just one sample to see if the output was still empty:

```
SalmonTE.py quant --reference=hs example/CTRL_1_R1.fastq.gz example/CTRL_1_R2.fastq.gz          [10/1825]
2018-01-30 21:03:31,698 Starting quantification mode
2018-01-30 21:03:31,698 Collecting FASTQ files...
2018-01-30 21:03:31,704 The input dataset is considered as a paired-ends dataset.
2018-01-30 21:03:31,705 Collected 1 FASTQ files.
2018-01-30 21:03:31,705 Quantification has been finished.
2018-01-30 21:03:31,706 Running Salmon using Snakemake
Building DAG of jobs...
2018-01-30 21:03:33,088 Building DAG of jobs...
Using shell: /bin/bash
2018-01-30 21:03:33,248 Using shell: /bin/bash
Provided cores: 1
2018-01-30 21:03:33,249 Provided cores: 1
Rules claiming more threads will be scaled down.
2018-01-30 21:03:33,249 Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       collect_abundance
        2
2018-01-30 21:03:33,250 Job counts:
        count   jobs
        1       all
        1       collect_abundance
        2

2018-01-30 21:03:33,251 
rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1
2018-01-30 21:03:33,251 rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1

2018-01-30 21:03:33,251 
Finished job 1.
2018-01-30 21:03:36,798 Finished job 1.
1 of 2 steps (50%) done
2018-01-30 21:03:36,800 1 of 2 steps (50%) done

2018-01-30 21:03:36,802 
localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0
2018-01-30 21:03:36,803 localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0

2018-01-30 21:03:36,803 
Finished job 0.
2018-01-30 21:03:36,805 Finished job 0.
2 of 2 steps (100%) done
2018-01-30 21:03:36,805 2 of 2 steps (100%) done
Shutting down, this might take some time.
2018-01-30 21:03:36,806 Shutting down, this might take some time.
Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-01-30T210333.018463.snakemake.log
2018-01-30 21:03:36,807 Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-01-30T210333.018463.snake
make.log
```

And it still is empty:

```
cat SalmonTE_output/EXPR.csv
TE
```

> This looks a different issue to #7, but the origin of the problems are same

I suspected that but did not test enough to make sure. I hope that this new error report helps a little to fix the bug.

Thanks,
António

**Comment by hyunhwaj** [comment]
@adomingues, Could you let me know which version of `snakemake` you have? For the second command, I have the log message and have a non-empty `EXPR.csv` in another machine. If your version is lower than 4.x.x then can you update version of `snakemake`, and please rerun it?

```
⚡ ./SalmonTE.py quant --reference=hs example/CTRL_1_R1.fastq.gz example/CTRL_1_R2.fastq.gz
2018-01-30 14:28:14,765 Starting quantification mode
2018-01-30 14:28:14,765 Collecting FASTQ files...
2018-01-30 14:28:14,768 The input dataset is considered as a paired-ends dataset.
2018-01-30 14:28:14,768 Collected 1 FASTQ files.
2018-01-30 14:28:14,768 Quantification has been finished.
2018-01-30 14:28:14,768 Running Salmon using Snakemake
Building DAG of jobs...
2018-01-30 14:28:14,867 Building DAG of jobs...
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
2018-01-30 14:28:14,867 Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
2018-01-30 14:28:14,868 Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
2018-01-30 14:28:14,868 Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
2018-01-30 14:28:14,869 Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Using shell: /bin/bash
2018-01-30 14:28:14,878 Using shell: /bin/bash
Provided cores: 1
2018-01-30 14:28:14,879 Provided cores: 1
Rules claiming more threads will be scaled down.
2018-01-30 14:28:14,879 Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	run_salmon_gz
	3
2018-01-30 14:28:14,879 Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	run_salmon_gz
	3

2018-01-30 14:28:14,879
rule run_salmon_gz:
    input: /tmp/tmpod6ygtxc/CTRL_1_R2.fastq.gz, /tmp/tmpod6ygtxc/CTRL_1_R1.fastq.gz, ./reference/hs
    output: /home/hwan/SalmonTE/SalmonTE_output/CTRL_1
    jobid: 2
    wildcards: sample_gz=CTRL_1
2018-01-30 14:28:14,879 rule run_salmon_gz:
    input: /tmp/tmpod6ygtxc/CTRL_1_R2.fastq.gz, /tmp/tmpod6ygtxc/CTRL_1_R1.fastq.gz, ./reference/hs
    output: /home/hwan/SalmonTE/SalmonTE_output/CTRL_1
    jobid: 2
    wildcards: sample_gz=CTRL_1

2018-01-30 14:28:14,879
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
Finished job 2.
2018-01-30 14:28:15,719 Finished job 2.
1 of 3 steps (33%) done
2018-01-30 14:28:15,719 1 of 3 steps (33%) done

2018-01-30 14:28:15,720
rule collect_abundance:
    input: /home/hwan/SalmonTE/SalmonTE_output/CTRL_1
    output: /home/hwan/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1
2018-01-30 14:28:15,720 rule collect_abundance:
    input: /home/hwan/SalmonTE/SalmonTE_output/CTRL_1
    output: /home/hwan/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1

2018-01-30 14:28:15,720
Finished job 1.
2018-01-30 14:28:16,220 Finished job 1.
2 of 3 steps (67%) done
2018-01-30 14:28:16,220 2 of 3 steps (67%) done

2018-01-30 14:28:16,221
localrule all:
    input: /home/hwan/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0
2018-01-30 14:28:16,221 localrule all:
    input: /home/hwan/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0

2018-01-30 14:28:16,222
Finished job 0.
2018-01-30 14:28:16,223 Finished job 0.
3 of 3 steps (100%) done
2018-01-30 14:28:16,223 3 of 3 steps (100%) done
Shutting down, this might take some time.
2018-01-30 14:28:16,223 Shutting down, this might take some time.
Complete log: /home/hwan/SalmonTE/.snakemake/log/2018-01-30T142814.855797.snakemake.log
2018-01-30 14:28:16,224 Complete log: /home/hwan/SalmonTE/.snakemake/log/2018-01-30T142814.855797.snakemake.log
```

Thank you,

Hwan

**Comment by hyunhwaj** [comment]
@adomingues, For the issue with your first command, did you see the same thing once you remove the `/tmp/tmpz9hnjo93/` directory? It must help me to figure out the problem is. The problem is not appearing in my environment, so it's tough to figure out on my side.

Thanks again,

Hwan

**Comment by adomingues** [comment]
> Could you let me know which version of snakemake you have?

Sorry for missing the information in the previous report. I realized that it was running the background, but did not pay much attention to it. The version is `4.5.0` which I believe is the latest. The system is:

```sh
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie
```

> For the issue with your first command, did you see the same thing once you remove the /tmp/tmpz9hnjo93/ directory? 

It persists even after deleting the tmp folder. 

Some **good news**. I decided to test it on my laptop (previously it in a server):

```sh
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

I repeated everything as before - installation in a python `virtualenv` in both - ad now everything works as expected. That is, using both `fastq` and  `fastq.gz` creates a fille `EXPR.txt` and it runs using all samples in the example directory. 

Apart form the different Linux version on both systems, a major difference is that in the server salmon TE was installed as a [module](http://lmod.readthedocs.io/en/latest/). Later today I will test a SalmonTE installation outside a module and let you if that works, though I don't think that will make a difference to be honest.

**Comment by adomingues** [comment]
> I will test a SalmonTE installation outside a module and let you if that works

Tested on the debian server. Still return the tmp related error. It could be a localized error, basically unique to that server, so maybe don't bother too much with it unless someone else reports a similar error? I was able to generate the results for my project by uncompressing the `fastq.gz` files, but I am happy to continue testing if that helps.

**Comment by hyunhwaj** [comment]
Dear @adomingues, 

Sorry, I recently didn't have any chance take a look your problem. I also eager to solve this problem, and I want to see error/log messages like [this].(https://github.com/hyunhwaj/SalmonTE/issues/8#issuecomment-361720251)

Can you also tell me which shell is you're using now?

Best Regards,

Hwan

**Comment by adomingues** [comment]
Sorry for the delay - I have quite busy preparing a poster (that will contain data generated with SalmonTE :))

logs:

```sh
SalmonTE.py quant --reference=hs example/CTRL_1_R1.fastq.gz example/CTRL_1_R2.fastq.gz
2018-02-09 13:21:32,190 Starting quantification mode
2018-02-09 13:21:32,190 Collecting FASTQ files...
2018-02-09 13:21:32,196 The input dataset is considered as a paired-ends dataset.
2018-02-09 13:21:32,197 Collected 1 FASTQ files.
2018-02-09 13:21:32,197 Quantification has been finished.
2018-02-09 13:21:32,197 Running Salmon using Snakemake
Building DAG of jobs...
2018-02-09 13:21:33,900 Building DAG of jobs...
Using shell: /bin/bash
2018-02-09 13:21:34,119 Using shell: /bin/bash
Provided cores: 1
2018-02-09 13:21:34,120 Provided cores: 1
Rules claiming more threads will be scaled down.
2018-02-09 13:21:34,120 Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	collect_abundance
	2
2018-02-09 13:21:34,121 Job counts:
	count	jobs
	1	all
	1	collect_abundance
	2

2018-02-09 13:21:34,122 
rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1
2018-02-09 13:21:34,123 rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1

2018-02-09 13:21:34,123 
Finished job 1.
2018-02-09 13:21:37,776 Finished job 1.
1 of 2 steps (50%) done
2018-02-09 13:21:37,777 1 of 2 steps (50%) done

2018-02-09 13:21:37,779 
localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0
2018-02-09 13:21:37,779 localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0

2018-02-09 13:21:37,780 
Finished job 0.
2018-02-09 13:21:37,781 Finished job 0.
2 of 2 steps (100%) done
2018-02-09 13:21:37,782 2 of 2 steps (100%) done
Shutting down, this might take some time.
2018-02-09 13:21:37,783 Shutting down, this might take some time.
Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-02-09T132133.824334.snakemake.log
2018-02-09 13:21:37,783 Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-02-09T132133.824334.snakemake.log
```
And 

```sh
cat /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-02-09T132133.824334.snakemake.log
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	collect_abundance
	2

rule collect_abundance:
    output: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1

Finished job 1.
1 of 2 steps (50%) done

localrule all:
    input: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0

Finished job 0.
2 of 2 steps (100%) done
Shutting down, this might take some time.
Complete log: /fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/.snakemake/log/2018-02-09T132133.824334.snakemake.log

```

**Comment by hyunhwaj** [comment]
@adomingues, This is tough to realize the issue, I may need more messages to figure this out. If you are fine and want to solve the issue with me, I will create a branch to generate more logs, and this will be helpful for the troubleshooting. Please let me know if are okay.

Hyun-Hwan Jeong

**Comment by adomingues** [comment]
I am happy to help @hyunhwaj. I might take a little longer than usual to report back because I am quite busy, but it should take little time on my part to run the tests. Go ahead and create the new test branch.

**Comment by hyunhwaj** [comment]
Thanks in advance, @adomingues. I will let you know once I am ready! Taking a longer time will be no problem.

Best,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
@adomingues 

I am curious you still have the same issue with the command, and could you put logs here with the latest version of `SalmonTE` again? 

Thank you,

Hyun-Hwan Jeong

**Comment by adomingues** [comment]
Hi @hyunhwaj, thank for your patience. I have tested the new version SalmonTE on the sever, that was giving us the problems, and as far as I can tell it is working

```bash
head SalmonTE_output/EXPR.csv
TE,CTRL_1,CTRL_2,TARDBP_1,TARDBP_2
ALU,0.0244029,0.0,0.0,0.0
AluJb,0.348222,0.0,0.0,0.0
AluJo,0.348222,0.0,0.0,0.0
AluJr,0.00675345,0.0,4319.19,0.0
AluJr4,0.0,0.0,0.0,0.0
AluSc,0.00324162,826.159,0.0,6613.12
AluSc5,0.0,0.0,0.0,0.0
AluSc8,67.7171,0.0,6780.67,0.0
AluSg,0.0,0.0,0.0,0.0

```

And the log:

```bash
cat /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/.snakemake/log/2018-06-05T093015.930394.snakemake.log
Building DAG of jobs...
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './reference/hs' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       collect_abundance
        4       run_salmon_gz
        6

rule run_salmon_gz:
    input: ./reference/hs, /tmp/tmpwjc_pj7u/TARDBP_2_R1.fastq.gz, /tmp/tmpwjc_pj7u/TARDBP_2_R2.fastq.gz
    output: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/TARDBP_2
    jobid: 3
    wildcards: sample_gz=TARDBP_2

Finished job 3.
1 of 6 steps (17%) done

rule run_salmon_gz:
    input: ./reference/hs, /tmp/tmpwjc_pj7u/CTRL_1_R1.fastq.gz, /tmp/tmpwjc_pj7u/CTRL_1_R2.fastq.gz
    output: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/CTRL_1
    jobid: 2
    wildcards: sample_gz=CTRL_1

Finished job 2.
2 of 6 steps (33%) done

rule run_salmon_gz:
    input: ./reference/hs, /tmp/tmpwjc_pj7u/CTRL_2_R1.fastq.gz, /tmp/tmpwjc_pj7u/CTRL_2_R2.fastq.gz
    output: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/CTRL_2
    jobid: 5
    wildcards: sample_gz=CTRL_2

Finished job 5.
3 of 6 steps (50%) done

rule run_salmon_gz:
    input: ./reference/hs, /tmp/tmpwjc_pj7u/TARDBP_1_R1.fastq.gz, /tmp/tmpwjc_pj7u/TARDBP_1_R2.fastq.gz
    output: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/TARDBP_1
    jobid: 4
    wildcards: sample_gz=TARDBP_1

Finished job 4.
4 of 6 steps (67%) done

rule collect_abundance:
    input: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/TARDBP_1, /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/CTRL_2, /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/CTRL_1, /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/TARDBP_2
    output: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 1

Finished job 1.
5 of 6 steps (83%) done

localrule all:
    input: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/SalmonTE_output/EXPR.csv
    jobid: 0

Finished job 0.
6 of 6 steps (100%) done
Shutting down, this might take some time.
Complete log: /fsimb/groups/imb-kettinggr/adomingues/projects/sandbox/SalmonTE/.snakemake/log/2018-06-05T093015.930394.snakemake.log
```

I think you can close the issue now. Thank you so much for this.

**Comment by hyunhwaj** [comment]
Great! Thanks for your valuable feedback.

Hyun-Hwan Jeong
